server:
  port: 9014

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/jwt-jdbc-userdetailsservice-customendpoint
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

security:
  claims-separator: --
  claim-roles-authorities: rolesAndAuthorities
  token-type: Bearer
  token-key: 12345
  token-validity: 10000000
