server:
  port: 9013

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/basic-jdbc-userdetailsservice-authprovider
    username: root
    password: root
  batch:
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
