server:
  port: 9012

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/basic-jdbc
    username: root
    password: root
  batch:
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none